package org.cocktail.trombino;
// Generated by the WOLips Templateengine Plug-in at 18 sept. 2006 15:53:17

import org.cocktail.fwkcktlwebapp.common.CktlUserInfo;
import org.cocktail.fwkcktlwebapp.common.database.CktlUserInfoDB;
import org.cocktail.fwkcktlwebapp.server.components.CktlWebPage;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSLog;
import com.webobjects.foundation.NSTimestamp;

public class LoginLocal extends CktlWebPage {

	public String login, password, errorMessage;
	public boolean authFailed = false;

	protected Application app = (Application) Application.application();
	public Session session;

	public LoginLocal(WOContext context) {
		super(context);
		session = (Session) session();

		WORequest aRequest = context.request();
		if (session.mandatoryLanguage() == null) {
			String lang = aRequest.stringFormValueForKey("lang");
			session.setMandatoryLanguage(lang);
		}
		session.createLocalizedStringsManager(this);

	}

	public void appendToResponse(WOResponse response, WOContext arg1) {
		super.appendToResponse(response, arg1);
		addLocalCss(response, "style.css");
		addLocalJScript(response, "lightbox.js");
		addLocalJScript(response, "trombiweb.js");
	}

	public WOComponent connecterUtilisateur() {

		if (login == null || login.equals("")) {
			authFailed = true;
			errorMessage = "Il faut donner un nom d'utilisateur";
			return null;
		}

		if (password == null || password.equals("")) {
			authFailed = true;
			errorMessage = "Il faut donner le mot de passe";
			return null;
		}

		String rootPW = app.config().stringForKey("APP_ADMIN_PASSWORD");

		CktlUserInfoDB lrUser = new CktlUserInfoDB(app.dataBus());
		lrUser.setRootPass(rootPW);
		lrUser.compteForLogin(login, password, true);
		if (lrUser.errorCode() == CktlUserInfo.ERROR_NONE) {
			errorMessage = setUserInfo(lrUser, session);
			authFailed = errorMessage != null;
		}
		else {
			authFailed = true;
			errorMessage = "Erreur : " + lrUser.errorMessage();
			return null;
		}
		if (authFailed || errorMessage != null) {
			return null;
		}
		// // Si le compte Grhum/LDAP existe, on regarde ou pas s'il a les droits sur la maquette pedagogique.
		if (session.getTypeTrombi() != Session.TROMBI_RECHERCHE) {
			EOQualifier qualLogin = EOQualifier.qualifierWithQualifierFormat("dlogLogin='" + login + "'", null);
			NSArray users = DBHandler.fetchData(session().defaultEditingContext(), "VDroitsLogin", qualLogin);
			if (users.count() > 0) {
				session.chargerDroitsUtilisateur();
			}
			else {
				authFailed = true;
				if (lrUser.errorCode() == CktlUserInfo.ERROR_COMPTE) {
					errorMessage = "Le compte n'existe pas, vérifier votre nom d'utilisateur.";
				}
				else
					if (lrUser.errorCode() == CktlUserInfo.ERROR_PASSWORD) {
						errorMessage = "Le mot de passe saisi est incorrect.";
					}
					else {
						errorMessage = "Echec de d'authentification.";
					}

				return null;
			}

		}
		login = null;
		password = null;
		return pageWithName(StartPage.class.getName());
	}

	public static String setUserInfo(CktlUserInfo user, Session session) {
		String errorMessage = null;
		session.setConnectedUserInfo(user);// pour le cas et connection automatique
		session.setLogin(user.login());
		session.setNomPrenom(user.nomEtPrenom());
		session.setEmail(user.email());
		session.setNoIndividu(user.noIndividu());

		String heure = FormatHandler.dateToStr(new NSTimestamp(), " @ %d/%m/%Y %H:%M");
		NSLog.out.appendln("connexion : login=" + user.login() + " noIndividu=" + user.noIndividu() + " le " + heure);

		// Si le compte Grhum/LDAP existe, on regarde ou pas s'il a les droits sur la maquette pedagogique.
		if (session.getTypeTrombi() != Session.TROMBI_RECHERCHE) {
			EOQualifier qualLogin = EOQualifier.qualifierWithQualifierFormat("dlogLogin='" + user.login() + "'", null);
			NSArray users = DBHandler.fetchData(session.defaultEditingContext(), "VDroitsLogin", qualLogin);
			if (users.count() > 0) {
				session.chargerDroitsUtilisateur();
			}
			else {
				if (user.errorCode() == CktlUserInfo.ERROR_COMPTE) {
					errorMessage = "Le compte n'existe pas, vérifier votre nom d'utilisateur.";
				}
				else
					if (user.errorCode() == CktlUserInfo.ERROR_PASSWORD) {
						errorMessage = "Le mot de passe saisi est incorrect.";
					}
					else {
						errorMessage = "Echec de l'authentification.";
					}

				return null;
			}

		}
		return errorMessage;
	}

}