package org.cocktail.trombino;
// Generated by the WOLips Templateengine Plug-in at 20 sept. 2006 15:52:45

import org.cocktail.fwkcktlwebapp.server.components.CktlWebComponent;

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;

public class Trombinoscope extends CktlWebComponent {

	public Application app = (Application) Application.application();
	public Session session;
	protected String pageTitle;

	public Trombinoscope(WOContext context) {
		super(context);
		session = (Session) session();
		session.setShowExtendedControls(true);
	}

	public void appendToResponse(WOResponse response, WOContext arg1) {
		super.appendToResponse(response, arg1);
		addLocalCss(response, "style.css");
		addLocalJScript(response, "lightbox.js");
		addLocalJScript(response, "trombiweb.js");
	}

	public void takeValuesFromRequest(WORequest aRequest, WOContext aContext) {
		super.takeValuesFromRequest(aRequest, aContext);
		String val = aRequest.stringFormValueForKey("comboFormation");
		FormatHandler.strToInteger(val);
	}

	public String getPageTitle() {
		return pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle;
	}

//	public WOComponent redirectToStartPage() {
//		session.setShowExtendedControls(false);
//		return pageWithName(StartPage.class.getName());
//	}

//	public WOComponent printTrombino() {
//		if (session.formationDataProvider().canPrint()) {
//			PdfReport nextPage = (PdfReport) pageWithName(PdfReport.class.getName());
//			nextPage.generateReport();
//			return nextPage;
//		}
//		else {
//			return null;
//		}
//	}

}